import React, { useRef } from 'react';
import { usePlan } from '../contexts/PlanContext';
import { Printer, Download } from 'lucide-react';

export default function Step5_Strategy() {
  const { plan } = usePlan();

  const handlePrint = () => {
    window.print();
  };

  // Helper to group initiatives by quarter
  const getInitiativesByQuarter = (q: string) => plan.initiatives.filter(i => i.quarter === q);

  return (
    <div className="space-y-6 pb-20">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">5. Strategic Plan</h1>
          <p className="text-slate-500 mt-2">Your one-page overview to communicate strategy clearly.</p>
        </div>
        <button onClick={handlePrint} className="bg-[#002060] text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-blue-900 transition">
          <Printer size={18} /> Print / Save PDF
        </button>
      </header>

      {/* The One Pager Container - Designed for A4/Landscape printing */}
      <div className="bg-white shadow-xl border border-slate-200 p-8 print:shadow-none print:border-0 print:p-0 mx-auto max-w-[1100px]">
        
        {/* Header */}
        <div className="border-b-4 border-[#002060] pb-4 mb-6 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-extrabold text-slate-900 uppercase tracking-tight">IT Strategic Plan</h1>
            <p className="text-slate-500 font-medium mt-1">2025 - 2026 Roadmap</p>
          </div>
          <div className="text-right">
            <div className="text-xl font-bold text-[#002060]">{plan.companyName || 'Company Name'}</div>
            <div className="text-sm text-slate-400">Generated by StratPlan</div>
          </div>
        </div>

        {/* Grid Layout */}
        <div className="grid grid-cols-12 gap-4">
          
          {/* Left Column: Drivers (Goals & Capabilities) */}
          <div className="col-span-4 space-y-4">
            {/* Business Objectives */}
            <div className="bg-blue-50 p-4 border-l-4 border-blue-600 h-full">
              <h3 className="font-bold text-[#002060] mb-3 uppercase text-sm tracking-wider">Business Objectives</h3>
              <ul className="list-disc pl-4 space-y-2 text-sm text-slate-700">
                {plan.interviews.slice(0,5).map((i, idx) => (
                   <li key={idx}>{i.keyObjectives.substring(0, 100)}{i.keyObjectives.length > 100 ? '...' : ''}</li>
                ))}
                {plan.interviews.length === 0 && <li className="italic text-slate-400">No objectives defined via interviews.</li>}
              </ul>
            </div>

            {/* Capabilities Focus */}
             <div className="bg-teal-50 p-4 border-l-4 border-teal-600 h-full">
              <h3 className="font-bold text-teal-900 mb-3 uppercase text-sm tracking-wider">Capability Focus</h3>
              <div className="space-y-2 text-sm text-slate-700">
                 {plan.capabilities.filter(c => c.targetMaturity > c.currentMaturity).slice(0,4).map(c => (
                   <div key={c.id} className="flex justify-between items-center">
                      <span>{c.name}</span>
                      <span className="text-xs font-mono bg-teal-100 text-teal-800 px-1.5 py-0.5 rounded">
                        {c.currentMaturity} → {c.targetMaturity}
                      </span>
                   </div>
                 ))}
              </div>
            </div>
          </div>

          {/* Middle/Right Column: Action Plan & Roadmap */}
          <div className="col-span-8 flex flex-col gap-4">
             
             {/* Strategic Roadmap */}
             <div className="border border-slate-200 p-4 rounded-sm flex-grow">
                <h3 className="font-bold text-slate-800 mb-4 uppercase text-sm tracking-wider border-b pb-2">Strategic Roadmap</h3>
                <div className="grid grid-cols-4 gap-2 text-center">
                   {['Q1', 'Q2', 'Q3', 'Q4'].map(q => (
                     <div key={q} className="bg-slate-50 p-2">
                        <div className="text-xs font-bold text-slate-500 mb-2">{q}</div>
                        <div className="space-y-2">
                          {getInitiativesByQuarter(q).map(i => (
                            <div key={i.id} className={`text-xs p-2 rounded text-left border-l-2 shadow-sm ${
                               i.strategicValue >= 8 ? 'bg-blue-100 border-blue-600 text-blue-900' : 'bg-white border-slate-300 text-slate-700'
                            }`}>
                              {i.name}
                            </div>
                          ))}
                        </div>
                     </div>
                   ))}
                </div>
             </div>

             {/* Metrics */}
             <div className="grid grid-cols-2 gap-4">
                <div className="bg-slate-50 p-4 border-t-4 border-slate-400">
                   <h3 className="font-bold text-slate-700 mb-3 uppercase text-sm tracking-wider">Key Metrics</h3>
                   <div className="space-y-2">
                      {plan.metrics.slice(0,4).map((m, i) => (
                        <div key={i} className="flex justify-between text-sm border-b border-slate-200 pb-1 last:border-0">
                          <span className="text-slate-600">{m.name}</span>
                          <span className="font-bold text-blue-600">{m.target}</span>
                        </div>
                      ))}
                      {plan.metrics.length === 0 && <span className="text-xs italic text-slate-400">No metrics defined.</span>}
                   </div>
                </div>

                <div className="bg-red-50 p-4 border-t-4 border-red-400">
                   <h3 className="font-bold text-red-900 mb-3 uppercase text-sm tracking-wider">Key Risks</h3>
                   {/* Risks are hardcoded for now or pulled from a separate list if we implemented the Risk tab fully */}
                   <ul className="list-disc pl-4 space-y-1 text-sm text-red-800">
                      <li>Talent shortage for AI initiatives</li>
                      <li>Budget constraints in Q3</li>
                   </ul>
                </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
}
